import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>YTU SKYLAB Bootcamp - React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
           <a href="https://yildizskylab.com">YTU Skylab Bootcamp - React</a>
        </h1>

        <p className={styles.description}>
          <a href="https://bulutbilisimciler.com">bulutbilisimciler.com</a> ile hızlıca test edin
        </p>

      </main>
    </div>
  )
}

export default Home
